// src/components/Button.svelte
<script lang="ts">
    let clazz;
    export { clazz as class };
</script>

<button
    on:click
    class={`z-10 py-2 px-4 text-sm font-medium relative overflow-hidden text-white duration-200 ease-in bg-purple-500 hover:bg-purple-400 hover:elevation-5 elevation-3 rounded button ${clazz}`}>
    <slot/>
</button>

// src/components/Button.tsx
import React from "react";

export default function Button(
  props: React.PropsWithChildren<{
    onClick: (e: React.MouseEvent<HTMLButtonElement>) => void;
  }>,
) {
  return (
    <button
      className="bg-purple-600 hover:bg-purple-700 transition p-1 rounded-md text-white"
      onClick={props.onClick}
    >
      {props.children}
    </button>
  );
}
