// src/components/Card.tsx
import React from "react";

export default function Card({ imageUrl, children, title, pretitle }: { imageUrl?: string, children?: React.ReactNode, title?: React.ReactNode, pretitle?: React.ReactNode }) {
    return <div className="bg-white rounded shadow w-full h-full overflow-hidden">
        {imageUrl && <img className="h-64 w-full object-cover object-top" src={imageUrl} />}
        <div className="p-2">
            {pretitle && <h4 className="text-md text-gray-600">{pretitle}</h4>}
            {title && <h3 className="font-bold text-lg">{title}</h3>}
            {children}
        </div>
    </div>
}

// src/components/Card.svelte
<script lang="ts">
  export let imageUrl = ''
</script>

<div class="bg-white rounded shadow w-full h-full overflow-hidden">
  {#if imageUrl}
      <img class="h-64 w-full object-cover object-top" src={imageUrl} />
  {/if}
  <div class="p-2">
    {#if $$slots.pretitle}
      <h4 class="text-md text-gray-600"><slot name="pretitle" /></h4>
    {/if}
    {#if $$slots.title}
      <h3 class="font-bold text-lg"><slot name="title" /></h3>
    {/if}
    <slot />
  </div>
</div>
