// src/routing/Route.tsx
import * as React from 'react';
import { useParams } from './router';

interface Props {
    path: string,
    exact: boolean
}

const parseMatch = (currentPage: string, path: string, exact: boolean) => {
    if (!currentPage)
        return currentPage === path;

    const pathParts = path.split('/');
    const pageParts = currentPage.split('/')

    if (exact && pageParts.length !== pathParts.length) return false

    const params = {}
    for (let i = 0; i < pathParts.length; ++i) {
        const pathPart = pathParts[i]
        const pagePart = pageParts[i]

        if (pathPart.startsWith(':')) {
            params[pathPart.replace(/(^:)|(\?$)/gi, '')] = pagePart

            // We can't have empty path parts, unless the user has said they can be
            // empty.
            if (!pathPart && !pagePart.endsWith('?')) return false;
            continue
        }

        if (pathPart !== pagePart) return false
    }

    return params
}

export default function Route({ path = '', exact = false, children }: Props & React.PropsWithChildren) {
    const { page } = useParams()
    const match = parseMatch(page, path, exact)

    if (!match) return null

    return typeof children === 'function'
        ? (children as any)(match)
        : children
}

// src/components/Route.svelte
<script lang="ts">
  import fragment from '../stores/fragment'

  export let path: string = ''
  export let exact: boolean = false

  const getMatchInfo = (page) => {
    if (!page)
        return page === path;

    const pathParts = path.split('/');
    const pageParts = page.split('/')

    if (exact && pageParts.length !== pathParts.length) return false

    const params = {}
    for (let i = 0; i < pathParts.length; ++i) {
      const pathPart = pathParts[i]
      const pagePart = pageParts[i]

      if (pathPart.startsWith(':')) {
        params[pathPart.replace(/(^:)|(\?$)/gi, '')] = pagePart

        // We can't have empty path parts, unless the user has said they can be
        // empty.
        if (!pathPart && !pagePart.endsWith('?')) return false;
        continue
      }

      if (pathPart !== pagePart) return false
    }

    return params
  }

  $: params = getMatchInfo($fragment.page) as { [key: string]: string };
</script>

{#if params}
  <slot {params} />
{/if}
