// src/components/MountainCard.tsx
import React from "react";
import { Mountain } from "../../svelte-src/stores/mountains";
import { allRoutes, getPicture } from "../utils/mountain";
import Card from "./Card";

export default function MountainCard(props: { mountain: Mountain }) {
    const routes = allRoutes(props.mountain)
    const picture = getPicture(props.mountain)
    return <Card imageUrl={picture}
        title={`${props.mountain.name} (${props.mountain.altitude})`}>
        {props.mountain.places.length + 1} areas,
        {routes.length} routes
    </Card>
}

// src/components/mountains/MountainCard.svelte
<script lang="ts">
  import { Mountain } from '../../stores/mountains'
  import { allRoutes, getPicture } from '../../utils/routes'
  import Card from '../Card.svelte'

  export let mountain: Mountain

  $: routes = allRoutes(mountain)
  $: imageUrl = getPicture(mountain)
</script>

<Card {imageUrl}>
  <span slot="title">{mountain.name} ({mountain.altitude})</span>
  <div>
    {mountain.places.length + 1} areas,
    {routes.length + 1} routes
  </div>
</Card>
